### ISSUE TITLE
mysql-主从配置(docker 版本)

### ISSUE THREAD

**Issue by houdq** [psycoHo/blog#113]
# mysql 主从

## docker-compose 实现

**master.cnf**

```yaml
[mysqld]
server-id = 1
log-bin = /var/log/mysql/mysql-bin.log
binlog_do_db = mydb


```

**slave.cnf**

```yaml
[mysqld]
server-id = 2
relay-log = /var/log/mysql/mysql-relay-bin.log
read-only = 1
```
**docker-compose 脚本**
```yml
version: '3'
services:
  master:
    image: mysql:latest
    container_name: master
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
    volumes:
      - ./master.cnf:/etc/mysql/conf.d/master.cnf
    ports:
      - 3306:3306

  slave:
    image: mysql:latest
    container_name: slave
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
    volumes:
      - ./slave.cnf:/etc/mysql/conf.d/slave.cnf
    ports:
      - 3307:3306
```

**主库配置**

```mysql
CREATE USER 'replication_user'@'%' IDENTIFIED BY 'your_password';
GRANT REPLICATION SLAVE ON *.* TO 'replication_user'@'%';
FLUSH PRIVILEGES;
```

```mysql
SHOW MASTER STATUS;
```
![image](https://github.com/houdq/blog/assets/9412449/5130a674-8ad3-433e-9828-adb51ee86764)

**从库配置**

```mysql

CHANGE MASTER TO
  MASTER_HOST='master',
  MASTER_USER='replication_user',
  MASTER_PASSWORD='your_password',
  MASTER_LOG_FILE='主服务器的File值',
  MASTER_LOG_POS=主服务器的Position值;
  
  #启动 slave
  START SLAVE;
```
查看从库信息
```
show slave status \G;
```

![image](https://github.com/houdq/blog/assets/9412449/c8126f14-eb64-466e-9925-9cde55e6e0bc)
