### ISSUE TITLE
string to jodaTime

### ISSUE THREAD

**Issue by psycoHo** [psycoHo/blog#8]
yml 文件中配置一下
```
jpa:

  properties:
    jadira:
      usertype:
        autoRegisterUserTypes: true
        databaseZone: UTC
        javaZone: UTC

```
